const actionTypes = {
  SET_ACTIVE_GROUP: 'SET_ACTIVE_GROUP',
  ADD_NEW_GROUP: 'ADD_NEW_GROUP',
  ADD_NEW_WORD: 'ADD_NEW_WORD',
  DELETE_ITEM_GROUP: 'DELETE_ITEM_GROUP',
  EDIT_ITEM_GROUP: 'EDIT_ITEM_GROUP',
}

export default actionTypes
