const actionTypes = {
  SET_ACTIVE_GROUP: 'SET_ACTIVE_GROUP',
  ADD_NEW_GROUP: 'ADD_NEW_GROUP',
  ADD_NEW_WORD: 'ADD_NEW_WORD',
  DELETE_GROUP_ITEM: 'DELETE_GROUP_ITEM',
  EDIT_GROUP_ITEM: 'EDIT_GROUP_ITEM',
  DELETE_WORD_ITEM: 'DELETE_WORD_ITEM',
  EDIT_WORD_ITEM: 'EDIT_WORD_ITEM',
}

export default actionTypes
